### ISSUE TITLE
Error in writing body of text to csv

### ISSUE THREAD

**Issue by celegant** [radiolarian/AO3Scraper#25]
Hi there, this has been brought up before but unfortunately I can't seem to figure out why it's happening (it's not just Excel for me), but the output of the ao3_get_fanfics csv looks like this:

![image](https://user-images.githubusercontent.com/81213198/117905366-106d2800-b2a1-11eb-802c-77ef24752637.png)

Not sure what's causing the text of the body to enter into the other rows, any insights on how to fix this?

EDIT: the breaks seem to happen with paragraph breaks in the actual text of the fic, but also in the middle of sentences with no delimiter other than a space?

**Comment by ssterman** [comment]
Unfortunately, this is just how Excel handles new lines when importing CSVs, even if protected by double quotes.  This CSV format is best for working with scripting, rather than Excel.  

You try could stripping out all newlines, or remove the "body" column before opening in Excel. Alternately, if you can use different software, Numbers (Apple's spreadsheet software) or LibreOffice (which is free) both handle this format (though LibreOffice has a character limit on cells that may introduce its own problems).
